In [1]:
from pipeline import pipeline
from esns import ESNSRelaxed

In [5]:
result = pipeline(
    dataset='WN18',
    model='TransE',
    negative_sampler=ESNSRelaxed,
    negative_sampler_kwargs=dict(
        index_column_size=1000,
        index_path="EII/WN18",
        sampling_size=100,
        q_set_size=50,
        similarity_metric="absolute"
    ),
    # Training configuration
    training_kwargs=dict(
        num_epochs=100,
        use_tqdm_batch=False,
        batch_size=8
    ),  
    # Runtime configuration
    random_seed=1235,
    device='cpu',
)

INFO:pykeen.datasets.utils:Loading cached preprocessed dataset from file:///C:/Users/Jannis/.data/pykeen/datasets/wn18/cache/47DEQpj8HBSa-_TImW-5JCeuQeRkm5NM
INFO:pykeen.triples.triples_factory:Loading from file:///C:/Users/Jannis/.data/pykeen/datasets/wn18/cache/47DEQpj8HBSa-_TImW-5JCeuQeRkm5NM/training
INFO:pykeen.triples.triples_factory:Loading from file:///C:/Users/Jannis/.data/pykeen/datasets/wn18/cache/47DEQpj8HBSa-_TImW-5JCeuQeRkm5NM/testing
INFO:pykeen.triples.triples_factory:Loading from file:///C:/Users/Jannis/.data/pykeen/datasets/wn18/cache/47DEQpj8HBSa-_TImW-5JCeuQeRkm5NM/validation
c:\Users\Jannis\miniconda3\envs\kge\lib\site-packages\pykeen\nn\representation.py:372: UserWarning: Directly use Embedding.max_id instead of num_embeddings.
  warnings.warn(f"Directly use {self.__class__.__name__}.max_id instead of num_embeddings.")
INFO:ESNSRelaxed:Loading EII EII/WN18/ESNSRelaxed_absolute_similarity_k1000_h.pkl
INFO:ESNSRelaxed:Loading EII EII/WN18/ESNSRelaxed_absolute_simila

0.013964176177978516
0.010971307754516602


Training epochs on cpu:   0%|          | 0/100 [00:00<?, ?epoch/s]

INFO:ESNSRelaxed:Loading EII EII/WN18/ESNSRelaxed_absolute_similarity_k1000_h.pkl
INFO:ESNSRelaxed:Loading EII EII/WN18/ESNSRelaxed_absolute_similarity_k1000_t.pkl


0.009974002838134766
0.009972572326660156
0.007978200912475586
0.014960050582885742
0.010970592498779297
0.009973526000976562
0.010970592498779297
0.008977174758911133
0.011969327926635742
0.007979154586791992
0.012965917587280273
0.008976221084594727
0.008975505828857422
0.012964963912963867
0.009974479675292969
0.00897669792175293
0.011967897415161133
0.008975028991699219
0.008976221084594727
0.008972406387329102
0.007979154586791992
0.014960289001464844
0.012967824935913086
0.012966394424438477
0.013964176177978516
0.013966798782348633
0.014959335327148438
0.012969255447387695
0.016955137252807617
0.010970354080200195
0.010969877243041992
0.015958309173583984
0.01097249984741211
0.0069828033447265625
0.008976459503173828
0.009973764419555664
0.008977413177490234
0.008974790573120117
0.008976936340332031
0.008975028991699219
0.008976221084594727
0.012965917587280273
0.007979154586791992
0.011969327926635742
0.012965202331542969
0.011969327926635742
0.008976936340332031
0.009975671768

0.007938146591186523


RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous

In [3]:
import torch

t1 = torch.tensor([[1, 9, 12, 5, 24], [1,0,3,9,2]])
t2 = torch.tensor([1, 24])

# Create a tensor to compare all values at once
compareview = t2.repeat(t1.shape[1],1).T

In [4]:
fruit = "Apple"
answer = ('Yes' if fruit == 'Apple' else 'No')

In [5]:
answer

'Yes'

In [6]:
compareview

tensor([[ 1,  1,  1,  1,  1],
        [24, 24, 24, 24, 24]])

In [7]:
test = [8,3,4]
for i in enumerate(test):
    print(i)

(0, 8)
(1, 3)
(2, 4)


In [8]:
import torch
test1 = torch.tensor([[1,2,3], [6,4,5], [7,8,9]])
test1.index_select(dim=0, index=torch.tensor([0,2,1,0,2,1,0,0]))

test2 = torch.tensor([[2,2,2], [2,2,2], [2,2,2]])

test1 * test2

tensor([[ 2,  4,  6],
        [12,  8, 10],
        [14, 16, 18]])

In [24]:
test1.topk(k=2,dim=1,sorted=False)

torch.return_types.topk(
values=tensor([[3, 2],
        [6, 5],
        [9, 8]]),
indices=tensor([[2, 1],
        [0, 2],
        [2, 1]]))

In [9]:
test1[..., 2] = torch.tensor(test)
test1

tensor([[6, 6, 6],
        [6, 4, 6],
        [7, 8, 6]])

In [5]:
import torch
import torch.nn.functional as F

test = torch.tensor([6,6,6])

F.pad(input=test, pad=[0,1], value=0)

tensor([6, 6, 6, 0])

In [14]:
test = torch.tensor([[[1,1],[1,2]], [[2,1], [2,2]]])
print(test.view(-1,2*2))

tensor([[1, 1, 1, 2],
        [2, 1, 2, 2]])


In [13]:
test = torch.tensor(list(range(3)))

torch.repeat_interleave(test, 2)

tensor([0, 0, 1, 1, 2, 2])

In [ ]:
import ftplib
import hashlib
import json
import logging
import os
import pathlib
import pickle
import time
from dataclasses import dataclass, field
from typing import (
    Any,
    ClassVar,
    Collection,
    Dict,
    Iterable,
    List,
    Mapping,
    MutableMapping,
    Optional,
    Tuple,
    Type,
    Union,
    cast,
)

import pandas as pd
import scipy.stats
import torch
from class_resolver.utils import OneOrManyHintOrType, OneOrManyOptionalKwargs
from torch.optim.optimizer import Optimizer

from ..constants import PYKEEN_CHECKPOINTS, USER_DEFINED_CODE
from ..datasets import get_dataset
from ..datasets.base import Dataset
from ..evaluation import Evaluator, MetricResults, evaluator_resolver
from ..evaluation.ranking_metric_lookup import normalize_flattened_metric_results
from ..losses import Loss, loss_resolver
from ..lr_schedulers import LRScheduler, lr_scheduler_resolver
from ..models import Model, make_model_cls, model_resolver
from ..nn.modules import Interaction
from ..optimizers import optimizer_resolver
from ..regularizers import Regularizer, regularizer_resolver
from ..sampling import NegativeSampler, negative_sampler_resolver
from ..stoppers import EarlyStopper, Stopper, stopper_resolver
from ..trackers import ResultTracker, resolve_result_trackers
from ..training import SLCWATrainingLoop, TrainingLoop, training_loop_resolver
from ..triples import CoreTriplesFactory
from ..typing import Hint, HintType, MappedTriples
from ..utils import (
    Result,
    ensure_ftp_directory,
    fix_dataclass_init_docs,
    get_json_bytes_io,
    get_model_io,
    load_configuration,
    normalize_path,
    random_non_negative_int,
    resolve_device,
    set_random_seed,
)
from ..version import get_git_hash, get_version